### ISSUE TITLE
[PP3] Schema

### ISSUE THREAD

**Issue by zsofitoth** [zsofitoth/RAWDATA_Project_Portfolio#30]
**stopwords**
- exclude words from wi

**wi** _(lemmatized)_
- lemma (+pos, sen, idx)
- word
- what: 1- title, 2- body

**wi_post**
- postId
- wiId
- score, count [ n(t) ]
  - creating weights - optimization needed

**assoc table** _(co-occurance, query expansion, term network)_
- w1
- w2
- rank
- code snippet 1 (from slide)
  - simple schema where grade is **n(d,t)**
  - runs for too long
```SQL
select w1.word,w2.word,count(*) grade from wi w1,wi w2
where w1.id=w2.id and w1.word<w2.word
group by w1.word,w2.word;
```
- code snippet 2 (from slide)
- we should consider optimization by indexing (wi table)
- use wi table's score to add a lower limit _score > 0.0002_ **AND** document frequency field to add another lower limit _n(t) > 20_
- low TF-IDF means not good candidate for close association
- low n(t) means terms occur in a few documents

```SQL
select w1.word,w2.word,count(*) grade from wi w1,wi w2
where w1.id=w2.id and w1.word<w2.word
and w1.tfidf>0.0002 and w2.tfidf>0.0002 and w1.nt>20 and w2.nt>20
group by w1.word,w2.word order by count(*) desc;
```
- last step is to store the result in a separate table, **assoc**

```SQL
SELECT wi1.word as w1, wi2.word as w2, count(*) as weight 
FROM wi_post as wip1
JOIN wi_post as wip2
ON wip1.PostId = wip2.PostId
JOIN wi as wi1
ON wip1.WiId = wi1.id
JOIN wi as wi2
ON wip2.WiId = wi2.id
WHERE wip1.sen = wip2.sen
AND wip1.idx = wip2.idx - 1
AND wi1.Score > 0.0002
AND wi1.Df > 20
AND wi2.Score > 0.0002
AND wi2.Df > 20
GROUP BY wi1.word, wi2.word
ORDER BY weight DESC;
```

**Comment by Vogete** [comment]
How about this: 

**wi**
- wiid (auto increment)
- word
- lemma (+pos)

**wi_post**
- postId
- wiId
- sen, idx
- score, count [ n(t) ]
  - creating weights - optimization needed
