### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by zsofitoth** [zsofitoth/RAWDATA_Project_Portfolio#6]
- [x] **Unit Testing Data Layer** 
   - [x] Questions - Zoli
   - [x] Answers - Zsofia
   - [x] Comments - Zsofia
   - [x] Users - Zoli
   - [x] Tags - Zoli
   - [x] PostHistory - Zoli
   - [ ] Bookmark
- [ ] **Unit Testing Web Service Layer**
   - [ ] QuestionsController - Zoli
   - [ ] AnswersController - Zsofia
   - [ ] CommentsController - Zsofia
   - [ ] UsersController - Zoli
   - [ ] TagsController - Zoli
- [ ] **Integration Testing**
   - [x] Questions
   - [x] Answers - Zsofia
   - [x] Comments - Zsofia
   - [x] Users - Zoli
   - [x] Tags - Zoli
   - [ ] Highlight
   - [ ] PostHistory
   - [ ] Bookmark

**Comment by MrAnno** [comment]
- [ ] **Happy Birthday!** - Zsofia 

Is it happy? I haven't _checked_.

**Comment by zsofitoth** [comment]
It is now. @MrAnno
